on:
  push:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    name: A job to say hello
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm cache clean --force
          npm install

      - name: Run hugollemos/actions@v1
        id: hello
        uses: hugollemos/actions@v1
        with:
          hugo: 'aqui ho'
          
      - name: Get the API response
        run: echo "API response ${{ steps.hello.outputs.response }}"
