on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: install dependecy
        run: npm i
        
      - name: hugollemos/actions@v1
        id: hello
        uses: hugollemos/actions@v1
        with:
          hugo: 'aqui ho'
      # Use the output from the `hello` step
      - name: Get the api
        run: echo " ${{ steps.hello.response }}"
